# Generated by Django 3.1.7 on 2021-04-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length='150')),
                ('autor', models.CharField(max_length=100)),
                ('acciones', models.TextField(max_length=450)),
                ('estatus', models.BooleanField(default=True)),
                ('cambioEstatus', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
