# Generated by Django 3.1.7 on 2021-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='cambioEstatus',
            field=models.CharField(default='Sin cambio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estatus',
            field=models.CharField(max_length=20),
        ),
    ]
