# Generated by Django 3.1.7 on 2021-04-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20210421_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='cambioEstatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
