# Generated by Django 3.1.7 on 2021-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20210421_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='acciones',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='cambioEstatus',
            field=models.CharField(default='Sin cambio', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
